export const FETCH_SCANS = "FETCH_SCANS";
export const FETCH_PLATFORMS = "FETCH_PLATFORMS";
export const FETCH_TERRITORIES = "FETCH_TERRITORIES";
export const FETCH_SPOT_STATISTICS = "FETCH_SPOT_STATISTICS";
export const SET_SELECTED_SCAN = "SET_SELECTED_SCAN";
export const SET_SELECTED_PLATFORM = "SET_SELECTED_PLATFORM";
export const SET_SELECTED_TERRITORY = "SET_SELECTED_TERRITORY";
export const SET_CLIENT_ID = "SET_CLIENT_ID";
